dashboard_app/urls.py
from django.urls import path
from . import views
from .views import solarapi

app_name="dashboard_app"
urlpatterns = [
  path("", views.dashboard, name="dashboard"),
  path("solarapi", solarapi.as_view(), name="solarapi"),
  path('retrieve', views.retrieve, name='retrieve'),
  path('optimize', views.optimize, name='optimize'),
]

dynamic_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard_app.urls")),
    path('', include("users.urls")),
]

users/urls.py
from django.urls import path
from . import views
from .views import signup_view
app_name = 'users'
urlpatterns = [
  path('', views.index, name='index'),
  path('login', views.login_view, name='login'),
  path('logout', views.logout_view, name='logout'),
  path('signup', signup_view.as_view(), name='signup')
]

dashboard_app/models.py
from django.db import models

# Create your models here.
class Sysdata(models.Model):
  user = models.CharField(max_length=64)
  system_name = models.CharField(max_length=100)
  system_capacity = models.CharField(max_length=100)
  module_type = models.CharField(max_length=100)
  losses = models.CharField(max_length=100)
  array_type = models.CharField(max_length=100)
  tilt = models.CharField(max_length=100)
  azimuth = models.CharField(max_length=100)
  lat = models.CharField(max_length=100)
  lon = models.CharField(max_length=100)

  class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'system_name'], name='no duplicate sysnames per user')
        ]

dashboard_app/forms.py
from django import forms

dashboard_app/views.py
from django.shortcuts import render
import os
import requests
import json
from django.http import HttpResponse, HttpResponseRedirect
from .models import Sysdata
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.utils import IntegrityError
from django.views import View
from django.utils.decorators import method_decorator
import asyncio
import httpx
import timeit


solar_api_key = os.environ.get('solar_api_key')
# Create your views here.

@login_required(login_url='/login')
def dashboard(request):
  systems = Sysdata.objects.filter(user=request.user.username)
  systemlist = []
  for system in systems:
    systemlist.append(system.system_name)
  return render(request, 'dashboard_app/dashboard.html', {
    'systemlist': systemlist,
    'user': request.user.username,
  })

@method_decorator(login_required, name="dispatch")
class solarapi(View):
  def get(self, request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
      params = {}
      for key in request.GET:
        params[key] = request.GET[key]
      params["api_key"] = solar_api_key
      outputdata = requests.get(
        f"https://developer.nrel.gov/api/pvwatts/v8.json",
        params=params).json()['outputs']
      returndata = {}
      for key in outputdata:
        returndata[key] = outputdata[key]
      return HttpResponse(json.dumps(returndata), content_type="application/json")
    else:
      print('Invalid request')

  def post(self, request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
      data = request.POST
      p = Sysdata(
        user = request.user.username,
        system_name = data['system_name'],
        system_capacity = data['system_capacity'],
        module_type = data['module_type'],
        losses = data['losses'],
        array_type = data['array_type'],
        tilt = data['tilt'],
        azimuth = data['azimuth'],
        lat = data['lat'],
        lon = data['lon']
      )
      try:
        p.save()
      except IntegrityError:
        return HttpResponse(json.dumps({'response': 'system name already exists'}))
      return HttpResponse(json.dumps({'system': data['system_name']}), content_type="application/json")
    else:
      print('invalid request')


@login_required(login_url='/login')
def retrieve(request):
  is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
  if is_ajax:
    if request.method == 'GET':
      system = Sysdata.objects.get(system_name=request.GET.get('system_name'), user=request.user.username)
      systemdata = {
        'api_key': solar_api_key,
        'system_capacity': system.system_capacity, 
        'module_type': system.module_type, 
        'losses': system.losses, 
        'array_type': system.array_type, 
        'tilt': system.tilt, 
        'azimuth': system.azimuth, 
        'lat': system.lat, 
        'lon': system.lon
      }
      params = dict(systemdata, api_key=f'{solar_api_key}')
      resp = requests.get(
        f"https://developer.nrel.gov/api/pvwatts/v8.json",
        params=params)
      outputdata = resp.json()['outputs']
      returndata = {}
      for key in outputdata:
        returndata[key] = outputdata[key]
      combinedreturndata = {'output': returndata, 'sysdata': systemdata}
      return HttpResponse(json.dumps(combinedreturndata), content_type="application/json")
    elif request.method == "DELETE":
      system_name = request.GET.get('system_name')
      Sysdata.objects.get(system_name=system_name, user=request.user.username).delete()
      return HttpResponse(json.dumps({'response': 'configuration deleted successfully'}), content_type="application/json")
  else:
      print("Invalid request")



@login_required(login_url='/login')
def optimize(request):
  is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
  if is_ajax:
    if request.method == 'GET':
      params = {}
      for key in request.GET:
        params[key] = request.GET[key]
      original_ac_annual = int(params['ac_annual'])
      tilt = 25
      azimuth = 180
      params.pop('ac_annual')
      params["api_key"] = solar_api_key
      params['azimuth'] = str(azimuth)
      params['tilt'] = str(tilt)
      response = requests.get(
        f"https://developer.nrel.gov/api/pvwatts/v8.json",
        params=params).json()
      ac_annual = int(response['outputs']['ac_annual'])
      for i in range(2):
        print(tilt)
        print(azimuth)
        print(ac_annual)

        params['azimuth'] = str(azimuth + 1)
        response = requests.get(
          f"https://developer.nrel.gov/api/pvwatts/v8.json",
          params=params).json()
        higherazimuthoutput = int(response['outputs']['ac_annual'])

        while higherazimuthoutput > ac_annual:
            print('moving to higher azi')
            ac_annual = higherazimuthoutput
            azimuth = azimuth + 1
            params['azimuth'] = str(azimuth + 1)
            response = requests.get(
              f"https://developer.nrel.gov/api/pvwatts/v8.json",
              params=params).json()
            higherazimuthoutput = int(response['outputs']['ac_annual'])
            
        params['azimuth'] = str(azimuth - 1)
        response = requests.get(
          f"https://developer.nrel.gov/api/pvwatts/v8.json",
          params=params).json()
        lowerazimuthoutput = int(response['outputs']['ac_annual'])

        while lowerazimuthoutput > ac_annual:
            print('moving to lower azi')
            ac_annual = lowerazimuthoutput
            azimuth = azimuth - 1
            params['azimuth'] = str(azimuth - 1)
            response = requests.get(
              f"https://developer.nrel.gov/api/pvwatts/v8.json",
              params=params).json()
            lowerazimuthoutput = int(response['outputs']['ac_annual'])

        params['azimuth'] = str(azimuth)

        params['tilt'] = str(tilt + 1)
        response = requests.get(
          f"https://developer.nrel.gov/api/pvwatts/v8.json",
          params=params).json()
        highertiltoutput = int(response['outputs']['ac_annual'])

        while highertiltoutput > ac_annual:
            print('moving to higher tilt')
            ac_annual = highertiltoutput
            tilt = tilt + 1
            if (tilt + 1) >= 91:
              break
            params['tilt'] = str(tilt + 1)
            response = requests.get(
              f"https://developer.nrel.gov/api/pvwatts/v8.json",
              params=params).json()
            highertiltoutput = int(response['outputs']['ac_annual'])
            
        params['tilt'] = str(tilt - 1)
        response = requests.get(
          f"https://developer.nrel.gov/api/pvwatts/v8.json",
          params=params).json()
        lowertiltoutput = int(response['outputs']['ac_annual'])

        while lowertiltoutput > ac_annual:
            print('moving to lower tilt')
            ac_annual = lowertiltoutput
            tilt = tilt - 1
            if (tilt - 1) < 0:
              break
            params['tilt'] = str(tilt - 1)
            response = requests.get(
              f"https://developer.nrel.gov/api/pvwatts/v8.json",
              params=params).json()
            lowertiltoutput = int(response['outputs']['ac_annual'])

        params['tilt'] = str(tilt)

        if int(params['tilt']) == 0:
          params['azimuth'] = 'any'
          break

      if original_ac_annual >= ac_annual:
        print('no change')
        return HttpResponse(json.dumps({'optimal_tilt': request.GET.get('tilt'), 'optimal_azimuth': request.GET.get('azimuth'), 'ac_annual': original_ac_annual}))
      return HttpResponse(json.dumps({'optimal_tilt': str(params['tilt']), 'optimal_azimuth': str(params['azimuth']), 'ac_annual': str(ac_annual)}), content_type="application/json")

dashboard_app/templates/dashboard_app/dashboard.html
{% extends "dashboard_app/layout.html" %}

{% block body %}
{% csrf_token %}
{% load static %}

<header class="sticky top-0 z-1 flex justify-between bg-rust p-2 border-b-2 border-rose-200 rounded-b-lg">
  <div>
    <form class="flex flex-col md:flex-row align-center" id="retrieve">
      <div class="text-center p-1">
        <label for="system_name" class="text-rose-200">System: </label>
        <select class='border p-2 bg-red-300 rounded-s-sx' name="system_name" id="system_name">
          <option value="">Choose a System</option>
        {% for system in systemlist %}
          <option value='{{ system }}'>{{ system }}</option>
        {% empty %}
          <div>No Systems Saved</div>
        {% endfor %}
        </select>
      </div>
      <div class="p-1">
        <button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 px-4 rounded active:bg-rose-300" type="submit">Retrieve</button>
        <button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 px-4 rounded active:bg-rose-300" type="button" id="deleteconfig">Delete</button>
      </div>
    </form>
  </div>
  <div class="flex flex-col md:flex-row text-rose-200">
    <p class="p-2">Hello, {{user}}!</p>
    <a href="{% url 'users:logout' %}"><button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 px-4 rounded active:bg-rose-300">Log Out</button></a>
  </div>
</header>
<!-- <gmp-map id='map' center="37.4220656,-122.0840897" zoom="10" map-id="DEMO_MAP_ID" style="height: 400px"></gmp-map> -->

<div class="relative flex flex-col p-[1rem] bg-rust">
  <div class="flex flex-col md:flex-row">
    <div id="map" class="md:h-[400px] max-w-[1098px] w-full h-[200px] shadow-lg shadow-stone-800"></div>
    <form id="form" class="flex flex-col p-[1rem] bg-rust max-w-[1241px] justify-between items-stretch">
      <div class="flex flex-col">
        <div class="flex flex-row">
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="system_capacity">system capacity (kWh) 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">This is the nameplate capacity of the system.</span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' type="number" min="0" max="500000" id="system_capacity" name="system_capacity">
          </div>
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="tilt">Tilt (degrees) 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">Angle of tilt from ground in degrees.</span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' class='border p-2 w-full bg-red-300 rounded-s-sx' type="number" min="0" max="90" id="tilt" name="tilt">
          </div>
        </div>
        <div class="flex flex-row">
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="losses">Losses (precentage) 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">System Losses as a precentage. Include Inverter inefficiency, thermal loss, etc.</span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' type="number" min="-5" max='95' id="losses" name="losses">
          </div>
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="azimuth">Azimuth (degrees) 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">Angle clockwise from north that the system faces. 180 is south facing, 0 is north facing. For one-axis, use axis of rotation for system direction. Anlge does not apply for two-axis systems. </span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' type="number" min="0" max="359" id="azimuth" name="azimuth">
          </div>
        </div>
      </div>
      <div class="flex flex-col">
        <div class="flex flex-row">
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="lat">Latitude 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">Range -90 to 90 with up to five decimal place precision</span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' type="number" step=".00001" min="-90" max="90" id="lat" name="lat">
          </div>
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="lon">Longitude 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">Range -180 to 180 with up to five decimal place precision</span>
              </div>
            </label>
            <input class='border p-2 w-full bg-red-300 rounded-s-sx m-2' type="numer" step='.00001' min="-180" max="180" id="lon" name="lon">
          </div>
        </div>
        <div class="flex flex-row">
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="module_type">module type 
              <div class="tooltip"><img 
                src="{% static 'images/tooltip.svg' %}"
                alt='tool tip image'
                width="15"
                heigth="15"/>
                <span class="tooltiptext">If module type is unkown, select Standard.</span>
              </div>
            </label>
            <select class='border p-2 w-full bg-red-300 rounded-s-sx m-2' name="module_type" id="module_type">
              <option value="0">Standard</option>
              <option value="1">Premium</option>
              <option value="2">Thin Film</option>
            </select>
          </div>
          <div class="text-center w-1/2 m-1">
            <label class="text-rose-200" for="array_type">array type <div class="tooltip"><img 
              src="{% static 'images/tooltip.svg' %}"
              alt='tool tip image'
              width="15"
              heigth="15"/>
              <span class="tooltiptext">For stationary systems without tracking, select Fixed.</span>
            </div></label>
            <select class='border p-2 w-full bg-red-300 rounded-s-sx m-2' name="array_type" id="array_type">
              <option value="0">Fixed - Open Rack</option>
              <option value="1">Fixed - Roof Mounted</option>
              <option value="2">1-Axis</option>
              <option value="3">1-Axis Backtracking</option>
              <option value="4">2-Axis</option>
            </select>
          </div>
        </div>
      </div>
      <div class="flex flex-row md:flex-col self-center">
        <button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 m-1 px-4 rounded w-[100px] active:bg-rose-300" type="submit">Submit</button>
        <button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 m-1 px-4 rounded w-[100px] active:bg-rose-300" type="button" id="save">Save</button>
      </div>
    </form>
  </div>
  <div class="flex justify-stretch flex-1 min-h-[0px] p-2 flex-wrap">
    <div class="flex-1 text-center p-2 border-r-1 border-rose-200">
      <p class="text-rose-200">Annual AC production</p><div class="text-rose-400 font-bold text-2xl" id="ac_annual">-- </div>
    </div>
    <div class="flex-1 text-center p-2 border-r-1 border-rose-200">
      <p class="text-rose-200">Annual Solar Radiation</p> <div class="text-rose-400 font-bold text-2xl" id="solrad_annual">--</div>
    </div>
    <div class="flex-1 text-center p-2 border-r-1 border-rose-200">
      <p class="text-rose-200">Capacity Factor <span class="tooltip"><img 
        src="{% static 'images/tooltip.svg' %}"
        alt='tool tip image'
        width="15"
        heigth="15"/>
        <span class="tooltiptext">The ratio of the system's predicted electrical output in the first year of operation to the nameplate output.</span>
      </span></p><div class="text-rose-400 font-bold text-2xl" id="capacity_factor">--</div>
    </div>
    <div class="flex-1 text-center p-2">
      <p class="text-rose-200">Optimal Tilt and Azimuth</p>
      <div class="text-rose-400 font-bold" id="optimizeddata">
      </div><div id="loadingsign" class="loadinghide"></div>
      <button class="bg-red-800 hover:bg-red-500 text-white font-bold py-2 px-4 rounded active:bg-rose-300" type="button" id="optimizeoutput">Optimize</button>
    </div>
  </div>
  <div class="flex flex-col min-[1098px]:flex-row flex-1 min-h-[0px] min-w-[355px] overflow-x-auto min-[580px]:overflow-x-visible">
    <div class="flex-auto min-w-[500px] barchart p-2 min-[1098px]:border-r-4 border-rust">
      <canvas id="barchart"></canvas>
    </div>
    <div class="flex-auto min-w-[500px] barchart p-2">
      <canvas id="barchart2"></canvas>
    </div>
  </div>
</div>
<footer class="bg-rust p-2 border-t-2 border-rose-200 rounded-t-lg text-center py-6 text-rose-200 mt-6">
  <p class="">© 2025 Scott Lynn. All rights reserved.</p>
</footer>

{% endblock %}

dashboard_app/templates/dashboard_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{% static 'dashboard_app/bundle.js' %}"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeyprKxr2cdmgdnBoFyQVXfIIo-S-IWfo&libraries=maps,marker&v=beta"
    defer></script>

  <!-- <link href="{% static 'dashboard_app/styles.css' %}" rel="stylesheet"> -->
  <title>Dashboard</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
<link href="{% static 'dashboard_app/styles.css' %}" rel="stylesheet">
</html>