dynamic_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard_app.urls")),
    path('', include("users.urls")),
]

users/urls.py
from django.urls import path
from . import views
from .views import signup_view
app_name = 'users'
urlpatterns = [
  path('', views.index, name='index'),
  path('login', views.login_view, name='login'),
  path('logout', views.logout_view, name='logout'),
  path('signup', signup_view.as_view(), name='signup')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
# Create your views here.
@login_required(login_url='/login')
def index(request):
  return HttpResponseRedirect(reverse('dashboard_app:dashboard'))


def login_view(request):
  if request.method == "POST":
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)
      return HttpResponseRedirect(reverse('dashboard_app:dashboard'))
    else:
      return render(request, 'users/login.html', {
        "message": "invalid credentials"
      })
  else:
    return render(request, "users/login.html")

def logout_view(request):
  logout(request)
  return render(request, "users/login.html", {
    "message": "Logged out."
  })

class signup_view(CreateView):
  form_class = UserCreationForm
  success_url = reverse_lazy("users:login")
  template_name = 'users/createaccount.html'

users/templates/users/createaccount.html
{% extends 'users/layout.html' %}

{% block body %}
  {% if message %}
    <div style="text-align: center; margin: auto;">{{message}}</div>
  {% endif %}
  <h2 style="text-align: center; margin: auto;">Sign up</h2>
  <form style="text-align: center; margin: auto;" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Users</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
  <div style="margin-top: 250px; display:flex; flex-direction: column; justify-content: center;">
  <div style="text-align: center; font-size: larger; color: brown;">This is a bare bones full-stack up with authentication, sessions, database, and API integration for obtaining expected annual energy output of a photovoltaic array based on system specifications, location and orientation. <br>
    <br>Feel free to create a quick account and and try it out. <br>
    <br>You can save system configurations and reference them later. <br>
    <br>Or just use username: <strong>user</strong> password: <strong>testuser</strong> to have a quick look around. <br>
  </div>
  {% if message %}
    <div style="text-align: center; margin: 10px;">{{message}}</div>
  {% endif %}
  <form style="display: flex; flex-direction: column;" action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div style="display: flex; justify-content: center; margin: 5px;">
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    </div>
    <div style="display: flex; justify-content: center; margin: 5px;">
    <input style="width: 100px; margin: 5px;" type="submit" value="Login">
    <button style="width: 100px; align-self: center;">
      <a href="{% url 'users:signup' %}">Creat Account</a>
    </button>
    </div>
  </form>
  </div>
  
{% endblock %}